version: '3.7'

services:
  mysql-master:
    image: sixeyed/mysql-replication:5.7
    ports:
     - '3306:3306'
    environment:
      SERVER_ID: '1'
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_ROOT_HOST: '%'
    networks:
     - mysql-net

  mysql-slave:
    image: sixeyed/mysql-replication:5.7
    ports:
     - '3307:3306'
    environment:
      SERVER_ID: '2'
      REPLICATION_MASTER_HOST: 'mysql-master'
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_ROOT_HOST: '%'
    networks:
     - mysql-net
          
networks:
  mysql-net: